version: "3"
volumes:
  data:
networks:
  wren:
    driver: bridge
services:
  bootstrap:
    image: ghcr.io/canner/wren-bootstrap:0.1.5
    pull_policy: always
    platform: linux/amd64,linux/arm64
    environment:
      DATA_PATH: /app/data
    volumes:
      - data:/app/data
    command: /bin/sh /app/init.sh
  wren-engine:
    image: ghcr.io/canner/wren-engine:0.9.3
    pull_policy: always
    platform: linux/amd64,linux/arm64
    expose:
      - 7432
    ports:
      - 8080:8080
    volumes:
      - data:/usr/src/app/etc
    networks:
      - wren
    depends_on:
      - bootstrap
  wren-ai-service:
    image: ghcr.io/canner/wren-ai-service:0.8.11
    pull_policy: always
    platform: linux/amd64,linux/arm64
    ports:
      - 5555
    environment:
      WREN_AI_SERVICE_PORT: 5555
      WREN_UI_PORT: 3000
      WREN_UI_ENDPOINT: http://wren-ui:3000
      QDRANT_HOST: qdrant
      LLM_OPENAI_API_KEY: sk-wPiVJOrgu2L3m7DUrWXq4KLJZwCrC3sM_jbq6_b4fST3BlbkFJiIgIq75ybkT_88hlMseL7BdP9LH8CRFyRQvdNInmcA
      EMBEDDER_OPENAI_API_KEY: sk-wPiVJOrgu2L3m7DUrWXq4KLJZwCrC3sM_jbq6_b4fST3BlbkFJiIgIq75ybkT_88hlMseL7BdP9LH8CRFyRQvdNInmcA
      GENERATION_MODEL: gpt-4o-mini
      ENABLE_TIMER: 1
      LOGGING_LEVEL: INFO
      PYTHONUNBUFFERED: 1
    networks:
      - wren
    depends_on:
      - qdrant
  ibis-server:
    image: ghcr.io/canner/wren-engine-ibis:0.9.3
    pull_policy: always
    platform: linux/amd64,linux/arm64
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      WREN_ENGINE_ENDPOINT: http://wren-engine:8080
      LOG_LEVEL: DEBUG
    networks:
      - wren
  qdrant:
    image: qdrant/qdrant:v1.11.0
    pull_policy: always
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - wren
  # If you want to use postgres for testing purpose, uncomment the following block
  # postgres:
  #   image: postgres:14-alpine
  #   platform: linux/amd64,linux/arm64
  #   ports:
  #     - 9432:5432
  #   volumes:
  #     - data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=secret
  #     - POSTGRES_USER=test
  #     - POSTGRES_DB=test
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   networks:
  #     - wren
